### ISSUE TITLE
Bug: Investigate Container crash on teammapper.org

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#560]
**Describe the bug**
```
 constraint: 'FK_336300b82c56a05f0317f229420',
2024-11-14 06:40:49.024580922 +0100 CET [web-1] table: 'mmp_node',
2024-11-14 06:40:49.024628557 +0100 CET [web-1] file: 'ri_triggers.c',
2024-11-14 06:40:49.024681775 +0100 CET [web-1] line: '2528',
2024-11-14 06:40:49.024467655 +0100 CET [web-1] at SubjectExecutor.executeInsertOperations (/app/teammapper-backend/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:435:42)
2024-11-14 06:40:49.024551470 +0100 CET [web-1] routine: 'ri_ReportViolation'
2024-11-14 06:40:49.024532808 +0100 CET [web-1] detail: 'Key (nodeMapId, nodeParentId)=(ce31a19b-402c-4c83-8c5d-70bb9b958115, 51ff2346-e0ec-4408-9fb3-5af0872f3f84) is not present in table "mmp_node".',
2024-11-14 06:40:49.024466653 +0100 CET [web-1] at PostgresQueryRunner.query (/app/teammapper-backend/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:260:25)
2024-11-14 06:40:49.024684608 +0100 CET [web-1] routine: 'ri_ReportViolation'
2024-11-14 06:40:49.024685453 +0100 CET [web-1] Node.js v22.2.0
2024-11-14 06:40:49.024276643 +0100 CET [web-1] '#FFC107',
2024-11-14 06:40:49.024252039 +0100 CET [web-1] '鱼类',
2024-11-14 06:40:49.024252271 +0100 CET [web-1] 0,
2024-11-14 06:40:49.024528206 +0100 CET [web-1] severity: 'ERROR',
2024-11-14 06:40:49.024552209 +0100 CET [web-1] severity: 'ERROR',
2024-11-14 06:40:49.024468508 +0100 CET [web-1] at EntityPersistExecutor.execute (/app/teammapper-backend/node_modules/typeorm/persistence/src/persistence/EntityPersistExecutor.ts:182:21)
2024-11-14 06:40:49.024580516 +0100 CET [web-1] schema: 'public',
2024-11-14 06:40:49.024533452 +0100 CET [web-1] position: undefined,
2024-11-14 06:40:49.024467182 +0100 CET [web-1] at InsertQueryBuilder.execute (/app/teammapper-backend/node_modules/typeorm/query-builder/src/query-builder/InsertQueryBuilder.ts:163:33)
2024-11-14 06:40:49.024279498 +0100 CET [web-1] 20,
2024-11-14 06:40:49.024567987 +0100 CET [web-1] detail: 'Key (nodeMapId, nodeParentId)=(ce31a19b-402c-4c83-8c5d-70bb9b958115, 51ff2346-e0ec-4408-9fb3-5af0872f3f84) is not present in table "mmp_node".',
2024-11-14 06:40:49.024440407 +0100 CET [web-1] 1,
2024-11-14 06:40:49.024552446 +0100 CET [web-1] code: '23503',
2024-11-14 06:40:49.050117673 +0100 CET [web-1] npm notice To update run: npm install -g npm@10.9.0
2024-11-14 06:40:49.024568958 +0100 CET [web-1] position: undefined,
2024-11-14 06:40:49.024685130 +0100 CET [web-1] }
2024-11-14 06:40:49.024551714 +0100 CET [web-1] },
2024-11-14 06:40:49.024469002 +0100 CET [web-1] at Object.diffAddedCallback (/app/teammapper-backend/src/map/services/maps.service.ts:211:11) {
2024-11-14 06:40:49.024568457 +0100 CET [web-1] hint: undefined,
2024-11-14 06:40:49.024469367 +0100 CET [web-1] length: 364,
2024-11-14 06:40:49.024551980 +0100 CET [web-1] length: 364,
2024-11-14 06:40:49.050090695 +0100 CET [web-1] npm notice New minor version of npm available! 10.7.0 -> 10.9.0
2024-11-14 06:40:49.024440040 +0100 CET [web-1] '',
2024-11-14 06:40:49.024569452 +0100 CET [web-1] internalPosition: undefined,
2024-11-14 06:40:49.024440763 +0100 CET [web-1] 0,
2024-11-14 06:40:49.050088781 +0100 CET [web-1] npm notice
2024-11-14 06:40:49.024468038 +0100 CET [web-1] at SubjectExecutor.execute (/app/teammapper-backend/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:137:9)
2024-11-14 06:40:49.024442850 +0100 CET [web-1] driverError: error: insert or update on table "mmp_node" violates foreign key constraint "FK_336300b82c56a05f0317f229420"
2024-11-14 06:40:48.987397283 +0100 CET [web-1] [Nest] 52 - 11/14/2024, 5:40:48 AM ERROR [WsExceptionsHandler] undefined
2024-11-14 06:40:49.024535361 +0100 CET [web-1] column: undefined,
2024-11-14 06:40:49.024247462 +0100 CET [web-1] ^
2024-11-14 06:40:49.024579556 +0100 CET [web-1] internalQuery: undefined,
2024-11-14 06:40:49.024280662 +0100 CET [web-1] 'normal',
2024-11-14 06:40:49.024579924 +0100 CET [web-1] where: undefined,
2024-11-14 06:40:49.024439676 +0100 CET [web-1] 121,
2024-11-14 06:40:49.050118319 +0100 CET [web-1] npm notice
2024-11-14 06:40:49.024280284 +0100 CET [web-1] 'normal',
2024-11-14 06:40:49.024441095 +0100 CET [web-1] -13.6629826712673,
2024-11-14 06:40:49.050112750 +0100 CET [web-1] npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
2024-11-14 06:40:49.024251385 +0100 CET [web-1] parameters: [
2024-11-14 06:40:49.024442472 +0100 CET [web-1] ],
2024-11-14 06:40:49.024551030 +0100 CET [web-1] line: '2528',
2024-11-14 06:40:49.024536094 +0100 CET [web-1] file: 'ri_triggers.c',
2024-11-14 06:40:49.024534890 +0100 CET [web-1] schema: 'public',
2024-11-14 06:40:49.024269997 +0100 CET [web-1] '#cddc39',
2024-11-14 06:40:49.024438845 +0100 CET [web-1] 'data:image/jpeg;base64...
```

Looks to me like someone is uploading a giant image which recks the server.

**Comment by JannikStreek** [comment]
Should be fixed with https://github.com/b310-digital/teammapper/pull/564 and  https://github.com/b310-digital/teammapper/pull/562 , lets see.
