### ISSUE TITLE
Bug: wrong uuid when undo is used

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#616]
**Describe the bug**

Apparently a wrong uuid (the internal mmp id) is used sometimes when undoing changes , see log entries:
```
     at async Object.diffDeletedCallback (/home/node/app/teammapper-backend/src/map/services/maps.service.ts:265:7) {
2024-12-14 09:00:35.320	
      at async Promise.all (index 9)
2024-12-14 09:00:35.320	
      at async <anonymous> (/home/node/app/teammapper-backend/src/map/services/maps.service.ts:266:30)
2024-12-14 09:00:35.320	
 ...
  driverError: error: invalid input syntax for type uuid: "map_1_node_11"
2024-12-14 09:00:35.320	
  **parameters: [ 'map_1_node_11', 'FILTERED_UUID' ],**
```

```
	
[Nest] 53  - 12/14/2024, 7:59:06 AM   ERROR [WsExceptionsHandler] invalid input syntax for type uuid: "map_1_node_151"
2024-12-14 08:59:06.242	
    at async WebSocketsController.pickResult (/home/node/app/teammapper-backend/node_modules/@nestjs/websockets/web-sockets-controller.js:96:24)
2024-12-14 08:59:06.242	
    at async MapsGateway.<anonymous> (/home/node/app/teammapper-backend/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
2024-12-14 08:59:06.242	
    at async MapsGateway.updateNode (/home/node/app/teammapper-backend/src/map/**controllers/maps.gateway.ts:159**:25)
2024-12-14 08:59:06.242	
    at async MapsService.updateNode (/home/node/app/teammapper-backend/src/map**/services/maps.service.ts:168**:26)
2024-12-14 08:59:06.242	
...
2024-12-14 08:59:06.242	
**QueryFailedError: invalid input syntax for type uuid: "map_1_node_152**"
```

**Comment by JannikStreek** [comment]
Reproducing the error:
- Import map with nodes using the old id format e.g. "map_1_node_1"
- Undo import step
=> Bang

[Root node (1).json](https://github.com/user-attachments/files/18139475/Root.node.1.json)

Possible solutions:
- Check on the client side _before uploading the map_ all ids, if uuids are used. Otherwise show toast with error
- Check on the server side before the map import is processed all ids being uuids. Otherwise return false.
